# Generated by Django 4.2.2 on 2023-09-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('BOARDROOM', 'Boardroom'), ('BASTION', 'Bastion'), ('KRAAIJ', 'Kraaij')], default='KRAAIJ', max_length=10)),
                ('reservable', models.BooleanField(default=False, help_text='This should only be unchecked if object is currently unreservable.')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.log')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Boatname')),
                ('boat_type', models.CharField(max_length=32)),
                ('person_capacity', models.IntegerField(default=2)),
                ('has_engine', models.BooleanField(default=False)),
                ('fleet', models.CharField(choices=[('LOEFBIJTER', 'Loefbijter'), ('CEULEMANS', 'Ceulemans'), ('OTHER', 'Other')], default='LOEFBIJTER', max_length=10)),
            ],
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='BoatReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
                ('engine_usage', models.DurationField()),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=32)),
            ],
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='GearReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
            ],
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Roomname')),
                ('capacity', models.IntegerField()),
            ],
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
            ],
            bases=('reservations.reservation',),
        ),
    ]
