# Generated by Django 4.2.2 on 2023-09-13 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complicationlog',
            name='reservable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservable'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.room'),
        ),
        migrations.AddField(
            model_name='gearreservation',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.gear'),
        ),
        migrations.AddField(
            model_name='boatreservation',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.boat'),
        ),
        migrations.AddField(
            model_name='boatreservation',
            name='skipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
