# Generated by Django 5.1.5 on 2025-03-10 09:58

import django.db.models.deletion
import django_extensions.db.fields
import loefsys.groups.models.group
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoefbijterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_foundation', models.DateField(verbose_name='Date of foundation')),
                ('date_discontinuation', models.DateField(blank=True, null=True, verbose_name='Date of discontinuation')),
                ('display_members', models.BooleanField(verbose_name='Display group members')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions')),
            ],
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('loefbijtergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.loefbijtergroup')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('groups.loefbijtergroup',),
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('loefbijtergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.loefbijtergroup')),
                ('mandatory', models.BooleanField(default=False, help_text='If this is checked new members should be assigned to this committee, any members that are part of this committee satisfy their committee_duty.')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('groups.loefbijtergroup',),
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fraternity',
            fields=[
                ('loefbijtergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.loefbijtergroup')),
                ('gender_base', models.PositiveSmallIntegerField(choices=[(0, 'Mixed'), (1, 'Female'), (2, 'Male')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Fraternities',
            },
            bases=('groups.loefbijtergroup',),
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Taskforce',
            fields=[
                ('loefbijtergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.loefbijtergroup')),
                ('requires_nda', models.BooleanField(default=False, help_text='If this is checked an NDA needs to be signed to be part of this taskforce.')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('groups.loefbijtergroup',),
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='YearClub',
            fields=[
                ('loefbijtergroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.loefbijtergroup')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('groups.loefbijtergroup',),
            managers=[
                ('objects', loefsys.groups.models.group.GroupManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='loefbijtergroup',
            constraint=models.CheckConstraint(condition=models.Q(('date_discontinuation__gte', models.F('date_foundation'))), name='date_discontinuation_gte_date_foundation', violation_error_message="The date of discontinuation can't be before the date of foundation"),
        ),
    ]
