# Generated by Django 4.2.2 on 2024-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='year',
            field=models.IntegerField(default=57),
        ),
        migrations.AlterField(
            model_name='yearclub',
            name='year',
            field=models.IntegerField(default=57),
        ),
    ]
