# Generated by Django 5.1.1 on 2024-10-04 13:13

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django_extensions.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('receive_newsletter', models.BooleanField(default=True, help_text='Receive the Newsletter', verbose_name='Receive newsletter')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('note', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoefbijterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Prefer not to say'), (2, 'Male'), (3, 'Female')], verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('show_birthday', models.BooleanField(verbose_name='Display birthday')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('street', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='please use the format <street> <number>', regex='^.+ \\d+.*')], verbose_name='Street and house number')),
                ('street2', models.CharField(max_length=100, verbose_name='Second address line')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.PositiveSmallIntegerField(choices=[(0, 'Active membership'), (1, 'Passive membership'), (2, 'Active exceptional membership'), (3, 'Passive exceptional membership'), (4, 'Alumnus')], default=0, verbose_name='Membership type')),
                ('start', models.DateField(default=datetime.date.today, help_text="The date the member's membership started", verbose_name='Membership start')),
                ('end', models.DateField(blank=True, default=None, help_text="The date the member's membership ends/ended.", null=True, verbose_name='Membership end')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.loefbijtermember', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last name')),
                ('initials', models.CharField(blank=True, max_length=20, verbose_name='Initials')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='Nickname')),
                ('display_name_preference', models.PositiveSmallIntegerField(choices=[(0, 'Show full name'), (1, 'Show full name with nickname'), (2, 'Show the nickname and last name'), (3, 'Show only the initials and the last name'), (4, 'Show only the first name'), (5, 'Show only the nickname')], default=0)),
                ('display_name', models.GeneratedField(db_persist=True, expression=models.Case(models.When(display_name_preference=1, then=django.db.models.functions.text.Concat(models.F('first_name'), models.Value(" '"), models.F('nickname'), models.Value("' "), models.F('last_name'))), models.When(display_name_preference=2, then=django.db.models.functions.text.Concat(models.F('nickname'), models.Value(' '), models.F('last_name'))), models.When(display_name_preference=3, then=django.db.models.functions.text.Concat(models.F('initials'), models.Value(' '), models.F('last_name'))), models.When(display_name_preference=4, then=models.F('first_name')), models.When(display_name_preference=5, then=models.F('nickname')), default=django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name'))), output_field=models.CharField(max_length=128))),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loefbijtermember',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='contacts.person'),
        ),
    ]
