# Generated by Django 5.1.1 on 2024-10-04 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loefbijtermember',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Organisation name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='contacts.contact')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('institution', models.CharField(max_length=32, verbose_name='Educational institution')),
                ('programme', models.CharField(max_length=32, verbose_name='Study programme')),
                ('student_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid student- or e/z/u-number.', regex='(s\\d{7}|[ezu]\\d{6,7})')], verbose_name='Student number')),
                ('rsc_number', models.CharField(blank=True, max_length=10, verbose_name='RSC card number')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_registration', to='contacts.loefbijtermember')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
