# Generated by Django 5.1.5 on 2025-03-10 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='contacts',
            field=models.ManyToManyField(related_name='events_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='events_organizer', to='groups.loefbijtergroup'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='mandatoryregistrationdetails',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='events.event', verbose_name='Event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'contact')},
        ),
    ]
